MACOSX_SDK_VERSION:        # [osx and x86_64]
  - "10.16"                # [osx and x86_64]
MACOSX_DEPLOYMENT_TARGET:  # [osx and x86_64]
  - "10.16"                # [osx and x86_64]
folly_build_ext:
  - None
  - "jemalloc"
fmt:
  - "9"
  - "8.0.1"
